# Rules for Yamllint.
# - https://github.com/adrienverge/yamllint
#
# Documentation about yamllint rules.
# - https://yamllint.readthedocs.io/en/stable/rules.html

rules:
  # --- Strict Syntax ---
  # These rules are inspired by StrictYAML syntax.
  # - https://hitchdev.com/strictyaml/
  #
  # There is no rule to forbid implicit typing with yamllint. We should avoid
  # using implicit types such as `null`, `true`, `false` and use strings
  # insteads or leave value empty for no value.
  #
  # The rules in summary:
  # - Enfore better type safety by requiring to quote strings.
  # - Warn about flow style, that is, braces and brackets.
  # - Forbid duplicate keys.
  # - Allow empty values. Let the parser decide the correct empty value.
  # - Require truthy values to `true` or `false` since they are commonly used
  #   in configurations.
  indentation:
    spaces: 'consistent'
    indent-sequences: true
  braces:
    forbid: true
    level: 'warning'
  brackets:
    forbid: true
    level: 'warning'
  document-end: 'disable'
  document-start: 'disable'
  empty-values: 'disable'
  key-duplicates: 'enable'
  key-ordering: 'disable'
  new-line-at-end-of-file: 'enable'
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true
  quoted-strings:
    quote-type: 'any'
    required: true
  truthy:
    allowed-values:
      - 'true'
      - 'false'
    check-keys: false
    level: 'warning'

  # --- Visual ---
  # Define visual formatting rules for concise, human-readable yaml.
  colons:
    max-spaces-before: 0
  hyphens:
    max-spaces-after: 1
  commas:
    max-spaces-before: 0
    min-spaces-after: 1
    max-spaces-after: 1
    level: 'warning'
  comments:
    require-starting-space: true
    min-spaces-from-content: 2
    ignore-shebangs: true
    level: 'warning'
  comments-indentation:
    level: 'warning'
  empty-lines:
    max: 1
    level: 'warning'
  new-lines:
    type: 'unix'
    level: 'warning'
  line-length: 'disable'
  trailing-spaces:
    level: 'warning'
